# Generated by Django 3.0.6 on 2020-07-09 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CoursesModel',
            fields=[
                ('courseid', models.AutoField(primary_key=True, serialize=False)),
                ('coursename', models.CharField(max_length=100)),
                ('courseFee', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='StudentModel',
            fields=[
                ('idno', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('contact', models.IntegerField(unique=True)),
                ('fee', models.FloatField()),
                ('subjects', models.ManyToManyField(to='app.CoursesModel')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FacultyModel',
            fields=[
                ('idno', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('contact', models.IntegerField(unique=True)),
                ('salary', models.FloatField()),
                ('subjects', models.ManyToManyField(to='app.CoursesModel')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
