# Generated by Django 3.0.6 on 2020-07-09 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='adminModel',
            fields=[
                ('admin_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=20)),
                ('contact_no', models.IntegerField(unique=True)),
                ('creation_date', models.DateField(default='09-07-2020')),
            ],
        ),
    ]
