# Generated by Django 3.0.6 on 2020-07-10 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20200709_2215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminmodel',
            name='creation_date',
            field=models.CharField(max_length=30),
        ),
    ]
